/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../components/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),3,'div',[['class',
      'flex-valign-center height-full flex-center']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵeld(1,0,(null as any),(null as any),
      2,'div',[['class','pad text-4x']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵeld(2,0,(null as any),(null as any),
      1,'a',[['class','no-a-style pad border-2 border-positive text-positive text-center hover-bg-positive hover-text-white'],
          ['href','Acker Apple Resume.pdf']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['Download Resume of Acker Dawn Apple']))],
      (null as any),(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i1.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('app',
    i1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Fja2VyYXBwbGUvcHJvamVjdHMvQWNrL3Jlc3VtZS9naC1wYWdlcy9zcmMvY29tcG9uZW50cy9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2Fja2VyYXBwbGUvcHJvamVjdHMvQWNrL3Jlc3VtZS9naC1wYWdlcy9zcmMvY29tcG9uZW50cy9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYWNrZXJhcHBsZS9wcm9qZWN0cy9BY2svcmVzdW1lL2doLXBhZ2VzL3NyYy9jb21wb25lbnRzL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9hY2tlcmFwcGxlL3Byb2plY3RzL0Fjay9yZXN1bWUvZ2gtcGFnZXMvc3JjL2NvbXBvbmVudHMvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiZmxleC12YWxpZ24tY2VudGVyIGhlaWdodC1mdWxsIGZsZXgtY2VudGVyXCI+PGRpdiBjbGFzcz1cInBhZCB0ZXh0LTR4XCI+PGEgY2xhc3M9XCJuby1hLXN0eWxlIHBhZCBib3JkZXItMiBib3JkZXItcG9zaXRpdmUgdGV4dC1wb3NpdGl2ZSB0ZXh0LWNlbnRlciBob3Zlci1iZy1wb3NpdGl2ZSBob3Zlci10ZXh0LXdoaXRlXCIgaHJlZj1cIkFja2VyIEFwcGxlIFJlc3VtZS5wZGZcIj5Eb3dubG9hZCBSZXN1bWUgb2YgQWNrZXIgRGF3biBBcHBsZTwvYT48L2Rpdj48L2Rpdj4iLCI8YXBwPjwvYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSw4QkFBd0Q7TUFBQTtNQUFBLDhCQUF5QjtNQUFBO1VBQUE7TUFBQSw4QkFBOEk7Ozs7b0JDQS9OO01BQUE7YUFBQTtVQUFBOzs7In0=
