/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../components/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['Hello World of Angular4']))],
      (null as any),(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i1.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('app',
    i1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0JlYXV0aXNvcy9wcm9qZWN0cy9BQ0svcmVzdW1lL2doLXBhZ2VzL3NyYy9jb21wb25lbnRzL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvQmVhdXRpc29zL3Byb2plY3RzL0FDSy9yZXN1bWUvZ2gtcGFnZXMvc3JjL2NvbXBvbmVudHMvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL0JlYXV0aXNvcy9wcm9qZWN0cy9BQ0svcmVzdW1lL2doLXBhZ2VzL3NyYy9jb21wb25lbnRzL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9CZWF1dGlzb3MvcHJvamVjdHMvQUNLL3Jlc3VtZS9naC1wYWdlcy9zcmMvY29tcG9uZW50cy9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIkhlbGxvIFdvcmxkIG9mIEFuZ3VsYXI0IiwiPGFwcD48L2FwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
